# Generated by Django 4.2.5 on 2023-09-29 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='name', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
                ('created_by', models.ForeignKey(blank=True, help_text='created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_category', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='updated by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='title', max_length=1024, null=True, unique=True)),
                ('content', models.TextField(blank=True, help_text='content', max_length=2048, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
                ('category_id', models.ManyToManyField(to='Blog.category')),
                ('created_by', models.ForeignKey(blank=True, help_text='created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_post', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='updated by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
